name: Build and Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sagetea
          password: dckr_pat_pDqQB441UonwLPfYZgqNWPpk2bw
      -
        name: Build Multiarch
        uses: docker/build-push-action@v3
        with:
          context: .
          file: /home/runner/work/docker-bench-security/docker-bench-security/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sagetea/docker-bench-security
